### ISSUE TITLE
Update for VCV 0.6?

### ISSUE THREAD

**Issue by SteveRussell33** [mlove-au/lufu-modules#7]
Are you still going to maintain this?

**Comment by mlove-au** [comment]
hi, sorry I didn't check back for sometime, and have't used VCV rack for awhile;. If you want, I can look into porting them to 0.6

**Comment by SteveRussell33** [comment]
Hi,
Thanks for getting back to me. 
I can't imagine there being much to do in updating to 0.6.

Kind Regards

**Comment by mlove-au** [comment]
ok. I'll have a look over the weekend.

**Comment by SteveRussell33** [comment]
These lines are missing from makefile

SLUG = lufu
VERSION = 0.6.0
RACK_DIR ?= ../..

I get this compile error:

Makefile:32: warning: overriding recipe for target 'dist'
../../plugin.mk:49: warning: ignoring old recipe for target 'dist'
g++ -I./third_party/ -Wsuggest-override -std=c++11  -DSLUG=lufu -fPIC -I../../include -I../../dep/include -DVERSION=0.6.0 -MMD -MP -g -O3 -march=nocona -ffast-math -fno-finite-math-only -Wall -Wextra -Wno-unused-parameter -DARCH_WIN -D_USE_MATH_DEFINES -c -o build/src/Recorder.cpp.o src/Recorder.cpp
src/Recorder.cpp:10:10: fatal error: components.hpp: No such file or directory
 #include "components.hpp"
          ^~~~~~~~~~~~~~~~
compilation terminated.
make: *** [../../compile.mk:65: build/src/Recorder.cpp.o] Error 1

**Comment by SteveRussell33** [comment]
Got it to compile using port-v0.6 branch
